trigger:
  batch: true
  branches:
    include:
      - dev/ssdt-*

stages:
- stage: Build
  displayName: Build SQL Database Project
  variables:
  - template: 'varaibles/ssdt-generic.yml'
  jobs:
  - template: templates/build.yml

- stage: DeployDev
  displayName: Deploy to DEV 
  variables:
  - template: 'varaibles/ssdt-generic.yml'
  jobs:
  - template: templates/deploy.yml
