trigger:
  batch: true
  branches:
    include:
      - dev/*

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: Build SQL Database Project

  jobs:
  - job: BuildSSDT
    displayName: Build Database project
    pool: 
      vmImage: 'windows-latest'
    steps:
    - task: MSBuild@1
      inputs:
        solution: '**/src/RocketCorp.SqlDb.DevOps.SqlServerDataTools/RocketCorp.SqlDb.DevOps.SqlServerDataTools.sqlproj'
        configuration: 'Release'
        clean: true
        maximumCpuCount: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/src/RocketCorp.SqlDb.DevOps.SqlServerDataTools/bin/Release'
        ArtifactName: 'sddt'
        publishLocation: 'Container'
