parameters:
- name: azureServiceConnection
  type: string

jobs:
- deployment: Deploy
  displayName: Deploy infrastructure SQL Database
  pool:
    vmImage: windows-latest
  variables:
    deploymentName: deploy.sql.database
    resourceGroup: az400-db
  environment: ZURE-DEV
  strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: ${{ parameters.azureServiceConnection }}
              keyVaultName: 'kv-az400-db'
              secretsFilter: 'adminPassword'
              runAsPreJob: true

          - task: AzureCLI@2
            displayName: Deploy SQL Server
            inputs:
              azureSubscription: ${{ parameters.azureServiceConnection }}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment group create \
                --resource-group $(resourceGroup) \
                --name $(deploymentName) \
                --template-file "$(Pipeline.Workspace)/env/main.bicep" \
                --parameters sqlServerName=$(sqlServerName) \
                --parameters adminName=$(adminName) \
                --parameters adminPassword=$(adminPassword)

          - task: SqlAzureDacpacDeployment@1
            displayName: DacpacTask
            inputs:
              azureSubscription:  ${{ parameters.azureServiceConnection }}
              ServerName: '$(sqlServerName).database.windows.net'
              DatabaseName: $(sqlDbName)
              SqlUsername: $(adminName)
              SqlPassword: $(adminPassword)
              DacpacFile: '$(Pipeline.Workspace)/ssdt/$(sqlDbName).dacpac'

          - task: AzureCLI@2
            displayName: Deploy SQL Database
            inputs:
              azureSubscription: ${{ parameters.azureServiceConnection }}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment group create \
                --resource-group az400-db \
                --name $(deploymentName) \
                --template-file "$(Pipeline.Workspace)/env/sql-database.bicep" \
                --parameters sqlServerName=$(sqlServerName) \
                --parameters sqlDbName=$(sqlDbName)

