SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [RocketCorp].[Departments]
(
	[Id] INT NOT NULL IDENTITY,
	[Name] NVARCHAR(255) NOT NULL, 
    CONSTRAINT [PK_Departments] PRIMARY KEY ([Id])
)
GO